### ISSUE TITLE
Watermark patch produces version check

### ISSUE THREAD

**Issue by wobblywhale** [km2ii/JP109A_TG-PLUS#1]
After copying the appropriate level0 file for the watermark patch and opening JAVPlayer, it comes up with the attached message. Dragging an exe into the window does nothing.

![image](https://user-images.githubusercontent.com/87220700/125153775-6d019c00-e199-11eb-97f3-c0dea1b5c183.png)

**Comment by km2ii** [comment]
This is just a watermark patch, not crack patch, you need the original licensed javplayer.exe (1.02) file,drag into the window.

**Comment by wobblywhale** [comment]
Thanks that worked, I needed to use the fully installed (extracted) 1.02 exe.

**Comment by grv888** [comment]
> This is just a watermark patch, not crack patch, you need the original licensed javplayer.exe (1.02) file,drag into the window.

Where i can get this version ?

**Comment by wobblywhale** [comment]
It's on Archive https://archive.org/details/JavPlayer102

**Comment by grv888** [comment]
ty

> It's on Archive https://archive.org/details/JavPlayer102
