### ISSUE TITLE
failed to execute script 'main' due to unhandled exception'dt'

### ISSUE THREAD

**Issue by 1805658335** [km2ii/JP109A_TG-PLUS#101]
The Config Tools.exe is error exhibit a window about this image, how do I this thing ？
![9ec0b8e473001ee9139fce6cc5f2250](https://user-images.githubusercontent.com/76620471/210416306-d2526f22-6faf-40c4-91f1-13a0b9c2ec48.png)

**Comment by IIJlOXOCIIAJl** [comment]
Strange, I got the same error even though everything was fine before python 3.10.6

**Comment by 1805658335** [comment]
@km2ii  can you help me?

**Comment by firebfm** [comment]
@IIJlOXOCIIAJl memo = This is an example. You erased this from config.ini. It was written just below the last m step.

**Comment by km2ii** [comment]
Error in config.ini, delete the config.ini, run it again and it will be fixed.

**Comment by IIJlOXOCIIAJl** [comment]
Thanks guys, this helped solve two problems at once.

**Comment by km2ii** [comment]
Check this setting.
![image](https://user-images.githubusercontent.com/55206195/213178615-23f7a03e-baa4-4e42-9cbe-a56831dea574.png)
