### ISSUE TITLE
tecogan-da error - RuntimeError: stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by toaster345** [km2ii/JP109A_TG-PLUS#103]
This is the error I get since updating my TG-PLUS to the latest version. I've tried many different things including reinstalling JP + TG-PLUS multiple times, tried using various different settings, different videos but I get the same result after a few seconds. The previous version worked flawlessly. RTX 3080.

tecogan.da error - RuntimeError: stack expects each tensor to be equal size, but got [3, 392, 726] at entry 0 and [3, 56, 96] at entry 10 [15780] Failed to execute script 'tecogan-da' due to unhandled exception!

**Comment by km2ii** [comment]
impossible to understand this error, [3, 392, 726] is neither a multiple of 4 or 8.
How is yours config.ini, did you put the tecogan-da in se stage?

**Comment by toaster345** [comment]
The weird thing is I never changed anything from the previous version, so I don't know why it would suddenly be doing this now?

These are my settings:

[main]
mode = TG-PLUS
debug = OFF

[mplus]
m1 = {'method': 'basicVSR-pp', 'model': 'basicVSR-pp-4x-std', 'para': '4X'}
m2 = {'method': 'downscale', 'model': '', 'para': '4x'}
m3 = {'method': 'tecogan-da', 'model': 'tecoGAN-da-8x-std', 'para': '8X'}
memo = This is an example.

[others]
imgext = png
dt = 3
skip_imgs = 14
crf = 22
resolution = 1920
n_count = 60
use_sharp = False
fp16 = False
offset_x = 0
offset_y = 0

[veai]
veaipath = C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe

[veai_theia_model_opt]
sharpen = 15
enhance-detail = 50
reduce-noise = 0

[veai_proteus_model_opt]
compression = 52
details = 24
blur = 9
noise = 7
halo = 12
preblur = -19

[veaidict]
ahq = ahq-11

[Author]
discord = kmkii#8701
gmail = ty4king@gmail.com

[mplus01]
m1 = {'method': 'basicVSR-pp', 'model': 'basicVSR-pp-4x-std', 'para': '4X'}
m2 = {'method': 'downscale', 'model': '', 'para': '4x'}
m3 = {'method': 'tecogan-da', 'model': 'tecoGAN-da-8x-std', 'para': '8X'}
memo = This is an example.

**Comment by km2ii** [comment]
The previous version had a problem that would cause differences between grouped images.
The new version will use the last 5 frames of the previous grouping as a warm-up to improve the image quality.
The second stage will report error because the input and output directory is the same directory (outputX).

If you still have a backup of the previous version, you can use TGMAIN\core_basicVSR_pp.cp37-win_amd64.pyd, replacing the current file, or wait for the next version.

**Comment by toaster345** [comment]
> If you still have a backup of the previous version, you can try use TGMAIN\core_tecogan_da.cp37-win_amd64.pyd, core_basicVSR_pp.cp37-win_amd64.pyd, replacing the current file.

This was the only thing that worked. Thanks.

**Comment by km2ii** [comment]
Closed and fixed in next version.
