### ISSUE TITLE
GPU Utilization 

### ISSUE THREAD

**Issue by AdamMacchiato** [km2ii/JP109A_TG-PLUS#13]
Hi , i Just check GPU Utilization is 0% and CPU is 70% when SE-4X is working , i have set the javplayer using GPU0 by TG and FFmpeg  , the performance is it right or anything wrong ?

**Comment by km2ii** [comment]
refer #2 , copy all .dll files into TGMAIN.

**Comment by AdamMacchiato** [comment]
[info] This mod is for learning and communication purposes only, it's completely free.
[info] Do not use it for any commercial purposes.
[info] By Dicord kmkii#8701 ,Twitter @kmkii2 .
[info] * mPlus: ['m1:tecogan:4:TG-STD', 'm2:denoise:tla', 'm3:tecogan:4:SE-4X']
[info] Running with TG-PLUS
[info] * mPlus1 * - tecogan-tg 4x.
main.exe --cudaID 0 --output_dir C:\JAV TEST\TG\output0 --output_name  --mode inference --input_dir_LR C:\JAV TEST\TG\input0 --num_resblock 16 --checkpoint C:\JAV TEST\TG\TG-MODEL\TG-STD --output_ext png --Mem_fraction 1.0



thank you , i just copy , then the screen keep stop here , not moving ...

**Comment by km2ii** [comment]
C:\JAV TEST
It is recommended to remove the spaces in the directory.

**Comment by AdamMacchiato** [comment]
[info] This mod is for learning and communication purposes only, it's completely free.
[info] Do not use it for any commercial purposes.
[info] By Dicord kmkii#8701 ,Twitter @kmkii2 .
[info] * mPlus: ['m1:tecogan:4:TG-STD', 'm2:denoise:tla', 'm3:tecogan:4:SE-4X']
[info] Running with TG-PLUS
[info] * mPlus1 * - tecogan-tg 4x.
main.exe --cudaID 0 --output_dir C:\Jav_Test2\TG\output0 --output_name  --mode inference --input_dir_LR C:\Jav_Test2\TG\input0 --num_resblock 16 --checkpoint C:\Jav_Test2\TG\TG-MODEL\TG-STD --output_ext png --Mem_fraction 1.0


Same problem ...not moving from here , if remove all .dll, come back to normal

**Comment by km2ii** [comment]
3000 series Requires cuda11 and cudnn8.1.1 environment.
Check your environment.
cd C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\extras\demo_suite
run bandwidthTest.exe and deviceQuery.exe to check.

**Comment by AdamMacchiato** [comment]
devicequery.exe Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA GeForce RTX 3080"
  CUDA Driver Version / Runtime Version          11.4 / 11.1
  CUDA Capability Major/Minor version number:    8.6
  Total amount of global memory:                 10240 MBytes (10737418240 bytes)
  (68) Multiprocessors, (128) CUDA Cores/MP:     8704 CUDA Cores
  GPU Max Clock rate:                            1740 MHz (1.74 GHz)
  Memory Clock rate:                             9501 Mhz
  Memory Bus Width:                              320-bit
  L2 Cache Size:                                 5242880 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               zu bytes
  Total amount of shared memory per block:       zu bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          zu bytes
  Texture alignment:                             zu bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 45 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.4, CUDA Runtime Version = 11.1, NumDevs = 1, Device0 = NVIDIA GeForce RTX 3080
Result = PASS

------------------------

[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: NVIDIA GeForce RTX 3080
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     25586.6

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     25576.1

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     581075.3

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

**Comment by AdamMacchiato** [comment]
[info] This mod is for learning and communication purposes only, it's completely free.
[info] Do not use it for any commercial purposes.
[info] By Dicord kmkii#8701 ,Twitter @kmkii2 .
[info] * mPlus: ['m1:tecogan:4:TG-STD', 'm2:denoise:tla', 'm3:tecogan:4:SE-4X']
[info] Running with TG-PLUS
[info] * mPlus1 * - tecogan-tg 4x.
main.exe --cudaID 0 --output_dir C:\Jav_Test2\TG\output0 --output_name  --mode inference --input_dir_LR C:\Jav_Test2\TG\input0 --num_resblock 16 --checkpoint C:\Jav_Test2\TG\TG-MODEL\TG-STD --output_ext png --Mem_fraction 1.0
Using TensorFlow backend.
input shape: [1, 44, 58, 3]
output shape: [1, 176, 232, 3]
Frame evaluation starts!!

now not moving from here ,,,,,, crying ....

**Comment by km2ii** [comment]
Try test package for 3000 series, includes runtime dll, fixes Vapoursynth bug,keep some warnings.
https://workupload.com/file/vuJE3JTMGMR

**Comment by AdamMacchiato** [comment]
[info] * mPlus1 * - tecogan-tg 4x.
main.exe --cudaID 0 --output_dir C:\Jav_Test2\TG\output0 --output_name  --mode inference --input_dir_LR C:\Jav_Test2\TG\input0 --num_resblock 16 --checkpoint C:\Jav_Test2\TG\TG-MODEL\TG-STD --output_ext png --Mem_fraction 1.0
WARNING:tensorflow:From tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
input shape: [1, 40, 58, 3]
output shape: [1, 160, 232, 3]
C:\Jav_Test2\TG\TGMAIN\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
WARNING:tensorflow:AutoGraph could not transform <function dense_image_warp at 0x000001D9010E2598> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function dense_image_warp at 0x000001D9010E2598>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function interpolate_bilinear at 0x000001D9010E2400> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function interpolate_bilinear at 0x000001D9010E2400>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Frame evaluation starts!!      Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!


this times show these message .....

**Comment by AdamMacchiato** [comment]
> refer #2 , copy all .dll files into TGMAIN.

But this work for my another PC with 2070S .......

**Comment by km2ii** [comment]
There  , Please make sure cudnn_ops_infer64_8.dll is in your library path!

**Comment by AdamMacchiato** [comment]
![螢幕擷取畫面 2021-08-17 135151](https://user-images.githubusercontent.com/88810328/129670841-f6a90f50-0bb2-4e72-8733-671cdbaaff7b.jpg)

one more qustion , if i deleted old TG main and model  , and copy the new version 1.08.17  TG main and  model , the imga test screen not moving like this , how to fix the problem >?

**Comment by AdamMacchiato** [comment]
> There , Please make sure cudnn_ops_infer64_8.dll is in your library path!

which  library path i should check ? thank you ... :D

**Comment by AdamMacchiato** [comment]
![螢幕擷取畫面 2021-08-17 145726](https://user-images.githubusercontent.com/88810328/129678684-08ae4f39-68e7-4061-8976-ee7a8072802f.jpg)


oh , i test 10 sec movie no problem , but go to full movie , so many message come out when TG working .... this is from 2070s PC ....

**Comment by km2ii** [comment]
In the C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin directory.
Copy the dll file to the TGMAIN directory

**Comment by AdamMacchiato** [comment]
> In the C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin directory.

I just try and still can,t work , i give up for 3080 .... crying....

**Comment by AdamMacchiato** [comment]
main.exe --cudaID 0 --output_dir C:\Jav Final\TG\output0 --output_name  --mode inference --input_dir_LR C:\Jav Final\TG\input0 --num_resblock 16 --checkpoint C:\Jav Final\TG\TG-MODEL\TG-STD --output_ext png --Mem_fraction 1.0
WARNING:tensorflow:From tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
input shape: [1, 56, 88, 3]
output shape: [1, 224, 352, 3]
C:\Jav Final\TG\TGMAIN\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
WARNING:tensorflow:AutoGraph could not transform <function dense_image_warp at 0x00000205FF5D7A60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function dense_image_warp at 0x00000205FF5D7A60>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function interpolate_bilinear at 0x00000205FF5D78C8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function interpolate_bilinear at 0x00000205FF5D78C8>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
 Saving image:73/73 [■■■■■■■■■■■■■■■■■■■■■■■■■] 100.0%
[info] Tecogan total time 3.13s 73 frames.
[info] * mPlus2 *  - denoise.
[info] Denoising please wait....
Output 24 frames in 1.84 seconds (13.04 fps)
Output 24 frames in 1.90 seconds (12.64 fps)
Output 24 frames in 2.05 seconds (11.72 fps)
[info] Denoise total time 2.97s.
[info] * mPlus3 * - tecogan-se 4x.
main.exe --cudaID 0 --output_dir C:\Jav Final\TG\output0 --output_name  --mode inference --input_dir_LR C:\Jav Final\TG\output0 --num_resblock 16 --checkpoint C:\Jav Final\TG\TG-MODEL\SE-4X --output_ext png --Mem_fraction 1.0
WARNING:tensorflow:From tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
input shape: [1, 224, 352, 3]
output shape: [1, 896, 1408, 3]
C:\Jav Final\TG\TGMAIN\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
WARNING:tensorflow:AutoGraph could not transform <function dense_image_warp at 0x000001E505DA7A60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function dense_image_warp at 0x000001E505DA7A60>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function interpolate_bilinear at 0x000001E505DA78C8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function interpolate_bilinear at 0x000001E505DA78C8>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
 Saving image:6/73 [■■□□□□□□□□□□□□□□□□□□□□□□□] 8.22%

**Comment by km2ii** [comment]
![image](https://user-images.githubusercontent.com/55206195/129733365-0cf148fe-64a7-4c42-84ef-790935f5e41c.png)
These dll files should also be used.

**Comment by AdamMacchiato** [comment]
thank you, actually GPU Load is 0% , but i am sure the speed is faster than before , and faster then 2070S , cause i check the "Tecogan total time "  , 22s 559 frames , is faster than 2070s ..... haha

**Comment by AdamMacchiato** [comment]
![螢幕擷取畫面 2021-08-17 213957](https://user-images.githubusercontent.com/88810328/129736111-d69359fa-9279-4eb6-a1e7-3951003cf447.jpg)

Its already exisitig ...

**Comment by AdamMacchiato** [comment]
so now final result is , that is the only wraning message ..... everthing still working .... right ?

**Comment by km2ii** [comment]
wraning  message can removed.
change to cuda tab
![image](https://user-images.githubusercontent.com/55206195/129736442-0fe4bcbf-ed63-484c-b782-a0fd194d18ff.png).

**Comment by AdamMacchiato** [comment]
Oh , where to set this  ?  

other things , i want to say , i test many time , 3080 at least faster than 2070s a double .....

**Comment by AdamMacchiato** [comment]
![螢幕擷取畫面 2021-08-17 213957](https://user-images.githubusercontent.com/88810328/129737800-13bf2896-e7f4-4a3d-9b81-8f3768a59f1e.jpg)

i dont have cuda option ?

**Comment by km2ii** [comment]
I don't know, maybe it's a different driver.
![image](https://user-images.githubusercontent.com/55206195/129738217-39bdb756-07a3-4f39-b383-ffcb6f867e81.png)

**Comment by AdamMacchiato** [comment]
Oh no ...... ha ha

**Comment by km2ii** [comment]
upload https://workupload.com/file/NYvUanSKLT6, remove wranings.

**Comment by km2ii** [comment]
upload https://workupload.com/file/NYvUanSKLT6, remove wranings.

**Comment by AdamMacchiato** [comment]
> upload https://workupload.com/file/NYvUanSKLT6, remove wranings.

Thank you so much  .....  Now i am trying full movie .... there is 2 problem :

1) when working around every 2-2.5hours , show 1 time error message , click ok will continue . that means cant auto run over night ...

2) TG saving pics quantity sometime is 1800/1800 , something is 14/14 , is it possible to make it large like  at least 1000 pics? because everytime load the M1 M2 M3 spend much time .... ha ha 

![螢幕擷取畫面 2021-08-17 145726](https://user-images.githubusercontent.com/88810328/129826993-b492591a-ecbd-4221-a07e-342332a88c25.jpg)

**Comment by AdamMacchiato** [comment]
Show again  , haha 

![螢幕擷取畫面 2021-08-18 142040](https://user-images.githubusercontent.com/88810328/129847847-ea02dad9-e8c1-4da6-81da-afd3e28ce337.jpg)

**Comment by km2ii** [comment]
It's a **good idea** to set a parameter for skip images. 👍
Because these directory almost has not contain mosaic. 
I'll put it in the next update.

**Comment by AdamMacchiato** [comment]
Woo ... its a great news for us  ....thanks alot .... yeah
