### ISSUE TITLE
i have some issue

### ISSUE THREAD

**Issue by allefforts** [km2ii/JP109A_TG-PLUS#14]
Error Type <class 'AttributeError'>
'NoneType' object has no attribute 'astype'
<FrameSummary file corem.py. line 228 in corem>
<FrameSummary file utis.py. line 326 in utis.inference_data_loader>
<FrameSummary file utis.py, line 318 in 
utils.inference_data_loader.preprocess_test>

how can i fix it?

**Comment by km2ii** [comment]
Unable to read image file, check TG/input0...

**Comment by km2ii** [comment]
I think the issue is gone.
