### ISSUE TITLE
With new TG-PLUS_v.1.08.17. verison gpu stop worked

### ISSUE THREAD

**Issue by grv888** [km2ii/JP109A_TG-PLUS#15]
Can u upload TG-PLUS_v.1.08.12 version?

![image](https://user-images.githubusercontent.com/63555514/129926180-4eb6aaec-9961-4922-89bc-0a828cc174b9.png)

everything works fine before

**Comment by km2ii** [comment]
re-upload https://workupload.com/file/bKRvKQVnCqW
cuda_dlls.rar can't work?

**Comment by grv888** [comment]
yes

**Comment by grv888** [comment]
now is everything fine ty
![image](https://user-images.githubusercontent.com/63555514/129933250-64dba4b7-a0cf-438b-aee9-a8415b72310e.png)

**Comment by km2ii** [comment]
08.17 version is adapted for 3000 series, 10xx, 20xx should be fine.
The good thing is 08.12 works.
