### ISSUE TITLE
about denoise paramter

### ISSUE THREAD

**Issue by FrankLinxzx** [km2ii/JP109A_TG-PLUS#16]
may km2ii write the denoise parameter name or introduction in readme,  thx a lot

**Comment by km2ii** [comment]
tla - mainly to reduce the flicker and noise caused by teco-SR.
blg - mainly to reduce image noise.
hyb - the blending mode.
There is not much difference, just use tla.

**Comment by FrankLinxzx** [comment]
> tla - mainly to reduce the flicker and noise caused by teco-SR.
> blg - mainly to reduce image noise.
> hyb - the blending mode.
> There is not much difference, just use tla.

whats tla come from?  another git project? thx

**Comment by km2ii** [comment]
Vapoursynth filter https://github.com/vapoursynth/vapoursynth.
You can modify tla.vpy in TG/TGMAIN/Vapoursynth, custom your denoise script.

**Comment by FrankLinxzx** [comment]
> Vapoursynth filter https://github.com/vapoursynth/vapoursynth.
> You can modify tla.vpy in TG/TGMAIN/Vapoursynth, custom your denoise script.

thx dude it helps me a lot
