### ISSUE TITLE
Applying the watermark patch

### ISSUE THREAD

**Issue by gummykage** [km2ii/JP109A_TG-PLUS#17]
Sorry to bother, i tried replacing level0 as in the instructions and this occurs in 1.09a:
![image](https://user-images.githubusercontent.com/9695713/130238568-641df43e-a40b-4f19-a2ca-8c992d806292.png)

Am I doing something wrong?

**Comment by km2ii** [comment]
Refer to issues #1 .

**Comment by km2ii** [comment]
Duplicate of #1
