### ISSUE TITLE
mPlus processing with SE-4X-R1 models crashes on error -Checkpoint validation failed

### ISSUE THREAD

**Issue by cornelius32** [km2ii/JP109A_TG-PLUS#18]
SE-4X-R1 model crashes during processing:

I am using TG-PLUS_v.1.08.17.rar version, redownloaded it twice, to see if the model files aren't corrupted. It didn't help. Base SE-4X model works.

![image](https://user-images.githubusercontent.com/89262657/130247880-57d6c62e-ed1c-4840-a02b-6eb7fb5b01da.png)

**Comment by km2ii** [comment]
yes , v0.1.08.20 update will fix this model.
