### ISSUE TITLE
update usage 

### ISSUE THREAD

**Issue by AdamMacchiato** [km2ii/JP109A_TG-PLUS#20]
Its great to see your new verisons, you are a big big inventor .... thank you so much ,,

for the new function can i have some questions ?

1) Fixed SE-4X-R1 model << whats different now ? 

2) I Love the Gaia Mode  , protues also good , but Gaia is more sharpen, what is your opinion ? 

3) m4 = downscale , may i know what is this use for ? why need downscale ?

4) i have many 480P video, do you thank i VEAI upscale to 720P  first , the quality of removing mosaic and details will better ? or same ? My test result is almost same ,,,,,

5) i still dont know how to re-Gen the config.ini  file ........crying

thank you inventor ...

**Comment by AdamMacchiato** [comment]
![螢幕擷取畫面 2021-08-21 180555](https://user-images.githubusercontent.com/88810328/130320213-53cc2562-1a0a-47bc-9fab-2bf3e0802366.jpg)

oh...just test super slow ?

**Comment by km2ii** [comment]
1.No diff, just fix SE-4X-R1 checking error.
2.It seems to be no support for the gaia models parameters grain-amount, grain-size, no suggestions.
3.After two tecogan-sr, the image will become large and denoise will waste a lot of time or exceed the memory limit get error. This is a balanced approach to speed up denoise.
4.Do not recommend this, only worse. You can consider removing mosaic first, then upscale may have some effect.
5.Just delete config.ini, and it will re-generated the next time.

super slow, turn debug ON. Check missing dll files in the warning messages.

**Comment by AdamMacchiato** [comment]
got it  , thank you so much :D

**Comment by grv888** [comment]
![image](https://user-images.githubusercontent.com/63555514/130338251-baa01d23-034e-4611-b45c-5865c8fa773b.png)
Hello, would you like share these files can't find them ty.

**Comment by AdamMacchiato** [comment]
> ![image](https://user-images.githubusercontent.com/63555514/130338251-baa01d23-034e-4611-b45c-5865c8fa773b.png)
> Hello, would you like share these files can't find them ty. Also it ask other two but i find them
> ![image](https://user-images.githubusercontent.com/63555514/130338305-03156b23-78de-45cf-88a3-a1a3e39495c2.png)

Copy the file cusolver64_10.dll to desktop , rename it cusolver64_11.dll , put it back to the lib , then fix it , :D

**Comment by AdamMacchiato** [comment]
actually if you install cuda 11.1 , fix all problem :D

**Comment by grv888** [comment]
Ye works, ty on my 970.

**Comment by grv888** [comment]
I mean new version after 12 want cuda 11 dll files. at least these 6 to fix gpu problem.
