### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by AdamMacchiato** [km2ii/JP109A_TG-PLUS#22]
![螢幕擷取畫面 2021-08-22 123607](https://user-images.githubusercontent.com/88810328/130342485-11916096-a685-45c1-800f-1d4693015c45.jpg)

how to fix this problem  ?

**Comment by km2ii** [comment]
Out of memory limit.This is the reason why set downscale parameter.
There are instructions in the old documentation.
![image](https://user-images.githubusercontent.com/55206195/130353856-75feec4f-e657-444a-a6a8-bad68258b7f4.png)

**Comment by AdamMacchiato** [comment]
got it , thank you , but i just have only 3 steps , 

480P video ,  using 2070s , 3080 no problem 

M1 : TG 4
M2 : Denoise
M3 : SE-4X 

The Error message always come out when SE-4X step , what should i do ?

**Comment by km2ii** [comment]
1.Yes, downscale should be executed first.
2.Maybe should add a function to start the task separately for the error reporting sequence. Let me think about how to do it.

**Comment by AdamMacchiato** [comment]
Thank you so much :D

**Comment by AdamMacchiato** [comment]
![image](https://user-images.githubusercontent.com/88810328/130549243-1b81dc89-52ae-4f8b-b03a-353d429e63fe.png)

oh what is this  ? first time full movie using new version v20

**Comment by AdamMacchiato** [comment]
So happy to tell that , downsclae first that go SE-4X , no more error message , and the step of SE-4X, much faster ..... haha ....
but do u think downscale will be deduct the image quality ? 

thank you so much ,,,, :D

**Comment by km2ii** [comment]
Downscale will be some effect. You can test it .

**Comment by AdamMacchiato** [comment]
after update this patch =  change to V22 right ?

TG-PLUS_v0.1.08.20.rar (498.07 MB)
https://workupload.com/file/UFstZpk5Byb

TG-Plus_v.0.1.08.22_patch.rar (114.70 KB)
Fixed skip_imgs bugs. Now can set resolution to NoLimited.

**Comment by km2ii** [comment]
Yes, but the next version will be updated soon.
