### ISSUE TITLE
tgmain.exe is flagged as gen:variant.bulz.566620 by my antivirus

### ISSUE THREAD

**Issue by artistx81** [km2ii/JP109A_TG-PLUS#23]
tgmain.exe is flagged as gen:variant.bulz.566620 by my antivirus

by bitdefender

**Comment by km2ii** [comment]
Scan your system kill virus.
If you suspect that there is a problem with this file, it is recommended not to use it.

**Comment by km2ii** [comment]
It can accept detection by anti-virus software.
![image](https://user-images.githubusercontent.com/55206195/130788663-b4204ad5-1235-4c71-9feb-2193d3d0a725.png)
