### ISSUE TITLE
Javplayer watermark patch issue

### ISSUE THREAD

**Issue by DuoxiXu** [km2ii/JP109A_TG-PLUS#26]
I am using Javplayer 1.09a. After applying the watermark patch for 1.09a, it's giving me errors:
System.NullReferenceException: Object reference not set to an instance of an object

![2021-08-30 104335](https://user-images.githubusercontent.com/44653540/131381732-23723428-7c1d-441d-9aa5-b728ded0c845.png)

**Comment by km2ii** [comment]
Each version corresponds to a different patch.  Try reinstall.

**Comment by DuoxiXu** [comment]
I tried every single level0 in the patch file, but none of them works. It might be because the Javplayer is different. Would it be possible to share the Javplayer you are using with me?

**Comment by km2ii** [comment]
The original link is down, it is archived here https://archive.org/details/JavPlayer109a.

**Comment by DuoxiXu** [comment]
Thanks for the link, now the watermark patch works perfectly!

**Comment by dj99999a** [comment]
Hi. Is there a watermark patch available for v1.11? Thanks!
