### ISSUE TITLE
Nice V30 update 

### ISSUE THREAD

**Issue by AdamMacchiato** [km2ii/JP109A_TG-PLUS#27]
I saw your sample , really really amazing !!! thank you your innovation !! 

and the sample you bring with setting of config.ini 

Questions : 
1) You set the skip_imgs = 0 ? how to set the value  ? sometime is 14 / 22 
2) The  protues model just keep all = 0 ? 
3) If the video is 1080p, need downscale first ? 

thank you !

**Comment by km2ii** [comment]
1. modify config.ini, or use configtools.
If the number of images in the directory is smaller than this parameter, it will skip the se ,denoise...steps.
2. protues model default is 0, other parameters will have an impact on the final result, you can test it yourself if you are interested.
3. be sure to add downscale:4 before ue-model, you can test to see the difference.

**Comment by AdamMacchiato** [comment]
- veai - prob-1 4x.
['C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe', '-i', 'C:\\Jav V20\\TG\\output0\\0000.png', '-o', 'C:\\Jav V20\\TG\\output0\\tmp', '-s', '4', '-m', 'prob-1', '-f', 'png', '--compression', '0', '--details', '30', '--blur', '30', '--noise', '0', '--halo', '0', '--preBlur', '0']
"C:/Jav V20/TG/output0/tmp"
<FileAppender::FileAppender> File name is empty. The appender will do nothing
<FileAppender::FileAppender> File name is empty. The appender will do nothing
<FileAppender::FileAppender> File name is empty. The appender will do nothing
Saving: C:/Jav V20/TG/output0/tmp

when process veai show this message, this is a problem or just ingore is ok ?

**Comment by km2ii** [comment]
Just ingore it.
