### ISSUE TITLE
Veai Error

### ISSUE THREAD

**Issue by zungmg** [km2ii/JP109A_TG-PLUS#28]
when i run it had error. Am I missing something?
![01](https://user-images.githubusercontent.com/38491131/131812796-62d91eab-0b57-462a-a208-8443483c0d4b.jpg)

**Comment by km2ii** [comment]
there is a bug . https://workupload.com/file/KKNx7n5sjwn copy to TG/TGMAIN/ overwrite orginal file.

**Comment by zungmg** [comment]
i instal VEAI 2.3 and it fixed
