### ISSUE TITLE
ConfigTool Python Error - cx_Freeze

### ISSUE THREAD

**Issue by wobblywhale** [km2ii/JP109A_TG-PLUS#3]
I get the following error when trying to run ConfigTool.exe

![image](https://user-images.githubusercontent.com/87220700/126094603-5fbaf32a-d1d8-4fc2-adb4-61d0b33cbe90.png)

I have Python 3.9 installed

**Comment by km2ii** [comment]
There are some issues here.
Try [https://thup.work/uploader/?mode=dl&id=26488&original=1](url)

**Comment by wobblywhale** [comment]
I don't know which file it was, but I overwrote something in the lib folder and it was fixed. 
Thanks again
