### ISSUE TITLE
works only with cuda 11.1?

### ISSUE THREAD

**Issue by gef12** [km2ii/JP109A_TG-PLUS#31]
I have cuda 11.0 installed and I can't install cuda 11.1 due to incompatibility with another application, it would have some way of working on 11.0, I did the installation, but I see little use of dedicated video card and Vram 0.2 in cuda 11.0

**Comment by km2ii** [comment]
CUDA 11.1 start support for NVIDIA GeForce RTX 30 Series. 11.0 is not supported.

**Comment by gef12** [comment]
thanks for the mod, I have GTX 1080 so it won't work.

**Comment by km2ii** [comment]
Install 11.1 directly, there is no conflict.
In my environment it is 10.0+11.1.
![image](https://user-images.githubusercontent.com/55206195/132619769-3e4307b0-9ebf-4918-8b86-d71d0bb403d3.png)

**Comment by gef12** [comment]
as I mentioned the other application is closed, and I have no way of defining which version it will use, it always chooses the most current one, generating errors and bugs.

**Comment by gef12** [comment]
Solution found: use cuda 11.1 libs inside TGMAIN directory, necessary libs cusolver64_11.dll and I can uninstall 11.1. and keep 11.0
