### ISSUE TITLE
mosaic cant detect

### ISSUE THREAD

**Issue by AdamMacchiato** [km2ii/JP109A_TG-PLUS#34]
Do you have any idea if the mosaic can not detect from old movie ? 
i upscale it from 480P to 720P first , will little bit better , but some of mosaic still cant detect ....

**Comment by km2ii** [comment]
Sorry can't help you, have no experience with this.

**Comment by ginpigin** [comment]
> 
> 
> Do you have any idea if the mosaic can not detect from old movie ?
> i upscale it from 480P to 720P first , will little bit better , but some of mosaic still cant detect ....

this is a javplayer problem, the definition of the mosaic goes even before the tg is processed. you can upscale through any video converter. too small mosaics will not be detected.

**Comment by AdamMacchiato** [comment]
Yeah right , i upscale and make it more sharpen , much much better  now ,

**Comment by AdamMacchiato** [comment]
So what is your next innovation ? haha
