### ISSUE TITLE
Error while using veai

### ISSUE THREAD

**Issue by LightningRS** [km2ii/JP109A_TG-PLUS#35]
I just installed Veai 2.3.0, and using TG-PLUS with patch2.
When I using veai in mplus, it shows the error dialog below:
![image](https://user-images.githubusercontent.com/54468001/135677217-65729eb9-b355-4696-8b37-2d7889f1c7dd.png)
After checking Config.ini, I found that the "veaidict" section was cleared (this happens every time starting tgmain.exe)
Before:
![image](https://user-images.githubusercontent.com/54468001/135677391-d29290ce-2936-4a80-912f-150390b07405.png)
After:
![image](https://user-images.githubusercontent.com/54468001/135677428-0531aa61-7a6b-404d-8d5d-07ecc1965af3.png)
Is that a bug? Or there's something wrong in my configuration process?

**Comment by grv888** [comment]
[veaidict]
ahq = ahq-11
alq = alq-12
alqs = alqs-1
amq = amq-12
amqs = amqs-1
gcg = gcg-5
ghq = ghq-5
prob = prob-1
thd = thd-3
thf = thf-4

my work for sure

**Comment by km2ii** [comment]
It may be caused by the installation of multiple versions of veai.
It is recommended to uninstall all versions and reinstall 2.3.0.

**Comment by LightningRS** [comment]
> It may be caused by the installation of multiple versions of veai. It is recommended to uninstall all versions and reinstall 2.3.0.

Thans for your precise help. I solved this problem by reinstalling the veai.
BTW, is that modules load from "AppData\Roaming\Topaz Labs LLC\Video Enhance AI\models" folder directly? Or from registry?
The version of veai I used before may be a portable version,  and I want to know the reason why it can't be detected.

**Comment by km2ii** [comment]
I am not able to answer this question precisely, only knows that there is a conflict between veai versions.
It will cause command line failure, model loading failure or other errors.

**Comment by LightningRS** [comment]
OK, thx. Have a nice day!
