### ISSUE TITLE
The error rate is very high

### ISSUE THREAD

**Issue by 1012352386** [km2ii/JP109A_TG-PLUS#43]
Sorry, my language is poor, roughly as follows
The error rate of video synthesis is very high
The most common is,GetThreadContext failed and Picture missing, etc
For longer videos, it is not only time-consuming
In case of failure, you need to start over
Hope to continue after correcting the wrong position
![21DE58E34A2D6CCA9C2712FE9387CFBA](https://user-images.githubusercontent.com/28804790/139295111-94ecc758-8507-46be-9e57-b1a74ea844a8.jpg)
![BE315A09FE8A4670BFFF37A8CFA2F981](https://user-images.githubusercontent.com/28804790/139295146-bdab663e-fc2c-4833-a5d4-39db4dee711d.jpg)

**Comment by km2ii** [comment]
I checked and did not find a bug with the "time.log" file.
If you can repeat the error, please upload TGMAIN/main_crash.log (please delete this file first).

**Comment by 1012352386** [comment]
OK, if the error is reported again in the follow-up, I will upload it

**Comment by km2ii** [comment]
Close this issue for now. If this problem occurs again, please post TGMAIN/main_crash.log here.
