### ISSUE TITLE
Difference between TG-STD and TG-8X and their usage

### ISSUE THREAD

**Issue by Hoshino609** [km2ii/JP109A_TG-PLUS#44]
What's the difference between the TG-STD and TG-8X model? Is it that TG-STD is upscaled "4 times" and TG-8x is upscaled "8 times"? So the only difference is the amount of super resolution applied (either 4X or 8X)?

And advice on how to best use TG-8X? Processing is slower compared to TG-STD, but might be worth it in some cases?

Thank you in advance

**Comment by km2ii** [comment]
It is clear that the model name shows the biggest difference.
I'm sorry I can't provide advice, this needs to be tested yourself.

**Comment by Hoshino609** [comment]
Okay, thank you. I close this issue.
