### ISSUE TITLE
veai uses png even when configured for jpg

### ISSUE THREAD

**Issue by sancho63** [km2ii/JP109A_TG-PLUS#48]
I occasionally try to use this but I've never gotten through a full clip. I've noticed a few times I ran out of disk space when I had ~100gb available. Using this leaves veai set for png output when veai is restarted outside op tg-plus so I'm fairly certain it's setting veai up for png. My config is set to use jpg so it seems to be ignoring that for veai

**Comment by km2ii** [comment]
![image](https://user-images.githubusercontent.com/55206195/153741986-3d487f41-1f52-4f1d-8017-3eb554cd3656.png)
![image](https://user-images.githubusercontent.com/55206195/153742356-3b53769c-c9d7-4300-b499-e3fad1f682e2.png)
