### ISSUE TITLE
Error in main.py and core_main.py when running main.exe

### ISSUE THREAD

**Issue by crusant** [km2ii/JP109A_TG-PLUS#49]
Hi, could you help me to solve the following error shown in the screenshot?

![error](https://user-images.githubusercontent.com/6889628/144686414-c866eed5-b970-49ea-a090-9f2d76f473f8.png)

**Comment by km2ii** [comment]
1.840m does not work properly with this mod.
2. It is clear that no output folder has been provided.
Closed and reopened if needed.
