### ISSUE TITLE
Can't work with RTX 3000 series gpu, just using cpu to operate

### ISSUE THREAD

**Issue by fakerchou** [km2ii/JP109A_TG-PLUS#5]
Not just me, several guys from fourm also claimed these plugs don't work for them.
For me, it's 3060 ,cuda11.1, cudnn 8.05, when Javplayer works, there is a 100% cpu usage for most part of process.
I copied the dlls to TGMAIN, not working, I think if there is a discord group will be help us reporting this errors.
I generated several videos with your plugs( using cpu), the TG+VAE result is fabulous! I can't use original javplayer back again. XD
Although the results are far better than the original javplayer, but the gpu adaptation seems need to be fix. 
Thanks for your working!

**Comment by km2ii** [comment]
1.Please refer  [#2 ],If the file is in the right place it should solve the gpu problem.
![image](https://user-images.githubusercontent.com/55206195/127322816-68f7c4a5-8aa3-4d15-942f-36dcd23dc7e4.png)
2.I blocked all warning messages for neatness of the output, which made debugging difficult.
You can download this, overwrite the original file ,backup the original file first.Post the error or warning message report here.
[https://github.com/km2ii/JP109A_TG-PLUS/blob/main/test/mn.cp36-win_amd64.pyd](url)
