### ISSUE TITLE
TG-Plus compatibility with new Javplayer v1.10

### ISSUE THREAD

**Issue by jrggg** [km2ii/JP109A_TG-PLUS#51]
EDIT JAN 1 2021: this is a universal TG-plus time limit to prevent people from maliciously selling this mod.

----
Original post:

Hi km2ii - javskii just released v1.10 for the base app yesterday, and I got the current TG-Plus (v0.1.10.24) to work flawlessly with it for the whole day (processed multiple vids without a hitch), but then it started giving the error "ERROR - Please update your TG-Plus!" whenever I processed something.

Since it worked flawlessly for a while, is there anything minor I can change for it to keep the compatibility? Or wait for an official new TG-plus release from you? Thanks!

![Screenshot 2022-01-01 014558](https://user-images.githubusercontent.com/96934980/147845372-0cc94f19-00ba-4434-8166-4407a673f675.png)

**Comment by PatWong0308** [comment]
Hi KM2II - It is not just V1.10- I'm running TG-Plus v 1.10.24 under 1.09a, than at around 6.00pm EST, the message "ERROR - Please update your TG-Plus!" showed up. Reinstalling cannot fix this. Thanks.

**Comment by PatWong0308** [comment]
Oh Sorry I missed a very important point , the date this message appeared was Dec 31 2021 6.00pm Canada Eastern time. Was this related to a new year 2022 issue ?

**Comment by km2ii** [comment]
It's not a millennial problem. It's actually time-limited,to prevent people from maliciously selling this mod.
 Here is a patch through 2022-03-31, Copy to TG\TGMAIN to overwrite the source [[**v1024_date_patch**](https://workupload.com/file/K9sLmUTKEEN) ].
Since javskii is already maintaining a new version of jvp, should focus more on the official version, 
whether this mod is updated or not.

**Comment by jrggg** [comment]
Thanks km2ii for the patch (that fixed it for me) and explanation!

Could you clarify what you mean by "Since javskii is already maintaining a new version of jvp, should focus more on the official version, whether this mod is updated or not." ?

Do you mean the new version of jvp from javskii could allow us lay users to set up similar sequential processing pipelines ourselves as you've enabled here with tg-plus?

**Comment by PatWong0308** [comment]
Thanks for the patch km2ii.

**Comment by km2ii** [comment]
> Do you mean the new version of jvp from javskii could allow us lay users to set up similar sequential processing pipelines ourselves as you've enabled here with tg-plus?

No, I think should respect the software authors and it is not polite to discuss hacking methods publicly. The official version has just started maintenance, and look forward to adding more features in the new version.

**Comment by jrggg** [comment]
> > Do you mean the new version of jvp from javskii could allow us lay users to set up similar sequential processing pipelines ourselves as you've enabled here with tg-plus?
> 
> No, I think should respect the software authors and it is not polite to discuss hacking methods publicly. The official version has just started maintenance, and look forward to adding more features in the new version.

That's totally fair! Do you mean we should all look forward to javskii adding more features in jvp's new version?

**Comment by Milincho** [comment]
Getting this same "ERROR - Please update your TG-Plus!" error now. Is there any update to the patch?
