### ISSUE TITLE
Error with javplayer 1.10

### ISSUE THREAD

**Issue by deedz1** [km2ii/JP109A_TG-PLUS#52]
Hi,

I keep getting this error regarding time.log. It seems to be present on longer recordings more often. Ive tried reinstalling everything twice but I still get this error

**Comment by deedz1** [comment]
I tried a new fresh install and now I get this error a lot

![image](https://user-images.githubusercontent.com/76548750/147866324-ddb3da04-7508-4800-9ddb-62631e2234ed.png)

Why is this happening?

**Comment by deedz1** [comment]
Another error I seem to be getting often is this 
![image](https://user-images.githubusercontent.com/76548750/147867513-5a9e0aef-7809-48d8-9f13-499c61d8be18.png)

Can you please explain what this means and what might be causing it?

**Comment by km2ii** [comment]
time.log is used for statistics, previously checked, there is no problem in normal work, may be in the task recovery will report an error.The second error, i will check it recently.

**Comment by jrggg** [comment]
I get the second error sometimes as well in the middle of processing something.

**Comment by deedz1** [comment]
> time.log is used for statistics, previously checked, there is no problem in normal work, may be in the task recovery will report an error.The second error, i will check it recently.

Hi, I noticed sometimes after a movie is done extracting (fast or safe), the time.log file is never created in the TGMAIN directory. It seems to happen randomly

**Comment by km2ii** [comment]
Closed and reopened if needed.
