### ISSUE TITLE
watermark_patch 1.09а

### ISSUE THREAD

**Issue by IIJlOXOCIIAJl** [km2ii/JP109A_TG-PLUS#53]
Hello.
Who can tell me why, I get such a window (see screenshot)
I am using 1.09a, changing the level0 file and for some reason I get this error.
![21](https://user-images.githubusercontent.com/95716704/149028966-fb345ba6-9945-44f6-a68c-290dabca2046.png)

**Comment by km2ii** [comment]
Reference #1
