### ISSUE TITLE
How to Download TG-plus?

### ISSUE THREAD

**Issue by WhiteBeard010** [km2ii/JP109A_TG-PLUS#54]
hey I see TG-plus for the first time and I would like to install it but I don't know how. I have read README_OLD.md but the links there do not work. can you help me there

**Comment by km2ii** [comment]
1. https://github.com/km2ii/JP109A_TG-PLUS/blob/main/README_BAK.md
2. [v1024_date_patch ](https://workupload.com/file/K9sLmUTKEEN),copy to TG\TGMAIN to overwrite the source.

**Comment by kocoman1** [comment]
the links are dead
