### ISSUE TITLE
Terrible results with older videos

### ISSUE THREAD

**Issue by DayDreamer5** [km2ii/JP109A_TG-PLUS#55]
Whenever I use TG Plus on older videos (480p) I get terrible results in comparison to HD videos and devensoring older videos with standard Javplayer as well. I've tried your example config files too (probably made for 720+). Any suggestion for config file settings to get better results for 480p video when compared to standard Javplayer?

**Comment by km2ii** [comment]
The mod is limited by the type of mosaic it corresponds to and does not solve all problems, so don't expect too much.
