### ISSUE TITLE
Error with javplayer 1.11

### ISSUE THREAD

**Issue by FrankLinxzx** [km2ii/JP109A_TG-PLUS#58]
i put it in  javplayer 1.11 test   and stop working  ,  i go to use 1.10
![擷取](https://user-images.githubusercontent.com/11344177/153752224-c4893a33-69cf-4e69-a145-2ec2e82a712d.PNG)

**Comment by km2ii** [comment]
It seems that the command parameters have been changed.

**Comment by km2ii** [comment]
Anyway, updated the adapted version.

**Comment by FrankLinxzx** [comment]
> Anyway, updated the adapted version.

i still use 1.10 with javplayer plus          ,1.11 for me  slow and no other option to optimize video
