### ISSUE TITLE
watermark patch for javplayer v1.11

### ISSUE THREAD

**Issue by suphamster** [km2ii/JP109A_TG-PLUS#59]
Is it possible to get one like it was made for older versions? Or at least a guide how to create such a patch (btw I've tried deleting strings like "Modified with JavPlayer" in level0\WmController.dat with no effect at all)...

**Comment by FrankLinxzx** [comment]
> Is it possible to get one like it was made for older versions? Or at least a guide how to create such a patch (btw I've tried deleting strings like "Modified with JavPlayer" in level0\WmController.dat with no effect at all)...

yes its possible  (i made it but i didnt want any  other use it to  share on websites  with no other limits like sehuatang  earning something, just enjoy by myself.

**Comment by km2ii** [comment]
/archive/KwGt6R59 km

**Comment by FrankLinxzx** [comment]
> /archive/KwGt6R59 km

where can i find it thx

**Comment by MediaMoots** [comment]
SGkgdGhlcmUhIHRoYW5rcyBmb3IgdGhlIHBhdGNoLCB3b3VsZCBpdCBiZSBwb3NzaWJsZSB0byB1cGRhdGUgaXQgZm9yIHZlcnNpb24gMS4xMWI/IHRoYW5rcyE=

https://www.base64encode.org/

**Comment by MediaMoots** [comment]
SGkgdGhlcmUhIHRoYW5rcyBmb3IgdGhlIHBhdGNoLCB3b3VsZCBpdCBiZSBwb3NzaWJsZSB0byB1cGRhdGUgaXQgZm9yIHZlcnNpb24gMS4xMWI/IHRoYW5rcyE=

https://www.base64encode.org/

**Comment by suphamster** [comment]
patch for v1.12 [https://twitter.com/Javski2/status/1541067860331548672](url) plz.

**Comment by km2ii** [comment]
> anti-wm patch for v1.12 https://twitter.com/Javski2/status/1541067860331548672 plz. btw anybody tested TG-STDx and TG-Z415 from javplayer dev, is it worth or TG-PLUS better?

Tried it seems to have a lot of problems, wait for the next version of the update. The new model does not surpass the STD, you can say that more than two years without progress.

**Comment by Milincho** [comment]
> > anti-wm patch for v1.12 https://twitter.com/Javski2/status/1541067860331548672 plz. btw anybody tested TG-STDx and TG-Z415 from javplayer dev, is it worth or TG-PLUS better?
> 
> Tried it seems to have a lot of problems, wait for the next version of the update. The new model does not surpass the STD, you can say that more than two years without progress.

What about an anti-wm patch for v1.12? could you release that or just tell us how it's done?

**Comment by km2ii** [comment]
Why the rush for this patch? There will be update 1.12a soon.

**Comment by Milincho** [comment]
> Why the rush for this patch? There will be update 1.12a soon.

1.12a released...    can you post the patch now, pretty please?  八(＾□＾*)

**Comment by suphamster** [comment]
+1. Btw anybody tested it - is it work fine with TG-PLUS and if it better than older JPL versions?

**Comment by km2ii** [comment]
aHR0cHM6Ly93b3JrdXBsb2FkLmNvbS9maWxlL0FHN2F3d2JiNXlWIGttCnNvcnJ5LCB0aGUgcGF0Y2ggbWF5IG5vdCBtYWRlIHB1YmxpYyBjb250aW51ZS4
@Milincho @suphamster

**Comment by Milincho** [comment]
> aHR0cHM6Ly93b3JrdXBsb2FkLmNvbS9maWxlL0FHN2F3d2JiNXlWIGttCnNvcnJ5LCB0aGUgcGF0Y2ggbWF5IG5vdCBtYWRlIHB1YmxpYyBjb250aW51ZS4 @Milincho @suphamster

Thank you VERY much!

**Comment by Milincho** [comment]
> aHR0cHM6Ly93b3JrdXBsb2FkLmNvbS9maWxlL0FHN2F3d2JiNXlWIGttCnNvcnJ5LCB0aGUgcGF0Y2ggbWF5IG5vdCBtYWRlIHB1YmxpYyBjb250aW51ZS4 @Milincho @suphamster

Mmm...   for some weird reason, using the patch makes setting the beginning of the loop point not working. The button stops doing anything.

https://i.imgur.com/rSE9CCu.png

**Comment by Milincho** [comment]
And the "Skip processing automatically" option in "General Recording Settings" can't be activated...

https://i.imgur.com/gMEAXLJ.png

**Comment by Milincho** [comment]
The watermark still shows up...   :-(

https://i.imgur.com/sHuvz3f.png

**Comment by km2ii** [comment]
aHR0cHM6Ly93b3JrdXBsb2FkLmNvbS9maWxlL2c4akMyekJVazl2CnVwZGF0ZSwgdGhlIHBhdGNoIG1heSBub3QgbWFkZSBwdWJsaWMgY29udGludWUu

**Comment by NickLin-Tw** [comment]
> aHR0cHM6Ly93b3JrdXBsb2FkLmNvbS9maWxlL2c4akMyekJVazl2CnVwZGF0ZSwgdGhlIHBhdGNoIG1heSBub3QgbWFkZSBwdWJsaWMgY29udGludWUu

Why does the page display "This file is not publicly accessible"?

**Comment by Milincho** [comment]
> > aHR0cHM6Ly93b3JrdXBsb2FkLmNvbS9maWxlL2c4akMyekJVazl2CnVwZGF0ZSwgdGhlIHBhdGNoIG1heSBub3QgbWFkZSBwdWJsaWMgY29udGludWUu
> 
> Why does the page display "This file is not publicly accessible"?

I think @km2ii means he doesn't want the patch out there publicly available, just for a few enthusiast that were interested enough to find this thread and keep asking him. :-)

**Comment by Milincho** [comment]
> aHR0cHM6Ly93b3JrdXBsb2FkLmNvbS9maWxlL2c4akMyekJVazl2CnVwZGF0ZSwgdGhlIHBhdGNoIG1heSBub3QgbWFkZSBwdWJsaWMgY29udGludWUu

Even this version still displays the watermark...   :-(

https://i.imgur.com/KOqHr2e.png

**Comment by Milincho** [comment]
@km2ii Will you be able to release a working patch, please? having that lame watermark on paid software is a total downer...

**Comment by Milincho** [comment]
Pretty Please
♡(ू•‧̫•ू⑅)

**Comment by Milincho** [comment]
Come on, @km2ii , give us some sugar...
