### ISSUE TITLE
Not working download links

### ISSUE THREAD

**Issue by AtenaNg** [km2ii/JP109A_TG-PLUS#6]
Thank you for sharing your wonderful work. It seems like the download links are not working properly. Would you check it? Or it possible to provide Google Drive link? 

Thank you.

**Comment by km2ii** [comment]
The thup.work is out of service.I don't know when it will be back up. 
It will take a few days to update some things and re-upload other servers.

**Comment by km2ii** [comment]
Upload finished.
https://github.com/km2ii/JP109A_TG-PLUS/blob/main/README.md
