### ISSUE TITLE
error type:<class'FlieNotFoundError'>

### ISSUE THREAD

**Issue by jhr-debug** [km2ii/JP109A_TG-PLUS#60]
hi km2ii I used tg-plus,but then it started giving the error:"error type:<class'FlieNotFoundError'> errorvalue:no such file or directory:'time log'<FrameSummary file core_runner.py,line 1365 in core_runner>".what should i do?please help me!thanks

**Comment by km2ii** [comment]
This issue has been fixed, please update to the last update.
