### ISSUE TITLE
console doesn't run in background 

### ISSUE THREAD

**Issue by deedz1** [km2ii/JP109A_TG-PLUS#61]
When selected console run in background in javplayer tecogan settings, the runGan.exe console still pops up. It did not use to do this in previous versions

![image](https://user-images.githubusercontent.com/76548750/156709355-9fc2611c-5a51-4b87-844f-0bea8b636ccb.png)

**Comment by km2ii** [comment]
In tg-plus mode, there is little point in hiding the console, as the veai window will also pop up.

**Comment by deedz1** [comment]
I don't use veai mode,

I run 8 instances at one time and the popups make the program unusable. Can you please make it so the  console can run in the background like older versions?

**Comment by km2ii** [comment]
Overwrite original file.
https://workupload.com/file/YuKtBuKh4N7

**Comment by km2ii** [comment]
I think this issue has been solved.
