### ISSUE TITLE
error: type<class 'indexError'>

### ISSUE THREAD

**Issue by 1805658335** [km2ii/JP109A_TG-PLUS#62]
- Hi km2ii, I am having a problem with Tgmain.exe running with a message that an error has occurred .Can you help me?
- ERROR
- Error type <class 'indexError'>
- error value :list index out of range 
- <FrameSummary file core_runner.py,line 1462 in core runner>
- <FrameSummary file core_runner.py,line 1026in core_runner_mplus>
- <frameSummary file core_runner.py line 727 in core_runner.call_denoise >
![LIKESSS](https://user-images.githubusercontent.com/76620471/157903384-dac28859-378e-4582-9df8-63cd6847cb05.png)

**Comment by Sulcorebutia** [comment]
Hi KM, I have the exact error frequently popping up. The following is my setup:
i7-10700
64GB ram
GTX1660 super 6GB ram

software setting:
javplayer 109, safe mode, h264 encode

[mplus]
m1 = tecogan:4:TG-STD
m2 = denoise:tla
m3 = veai:4:ahq

What other information shall I provide here?

**Comment by Sulcorebutia** [comment]
![Screenshot 2022-03-20 084916](https://user-images.githubusercontent.com/101955980/159143446-281562a7-c8ec-4a5d-b7a5-6ceae860c0e2.png)

**Comment by Sulcorebutia** [comment]
It happens to the denoise:tla stage. Will there any log files I shall upload here for your reference?

**Comment by km2ii** [comment]
This bug is fixed in versions after 02.14, download 02.26 package (https://workupload.com/file/eu74edfkhS8) or download the patch (https://workupload.com/file/BdtWUuFbZYb) to overwrite the source file location in the TG/ TGMAIN directory.

**Comment by Sulcorebutia** [comment]
Thanks Km2ii, the problem has been gone after applying the patch.

**Comment by FrankLinxzx** [comment]
> This bug is fixed in versions after 02.14, download 02.26 package (https://workupload.com/file/eu74edfkhS8) or download the patch (https://workupload.com/file/BdtWUuFbZYb) to overwrite the source file location in the TG/ TGMAIN directory.
THX IT works

**Comment by FrankLinxzx** [comment]
> > This bug is fixed in versions after 02.14, download 02.26 package (https://workupload.com/file/eu74edfkhS8) or download the patch (https://workupload.com/file/BdtWUuFbZYb) to overwrite the source file location in the TG/ TGMAIN directory.
> > THX IT works ( i use .24 version have problem too)

**Comment by 1805658335** [comment]
Now, I have another trouble
![eb20de6582909aba00e23141a6a652e](https://user-images.githubusercontent.com/76620471/161779085-7122e88e-e44a-406e-ae3b-47eb55a1e6e6.png)

**Comment by 1805658335** [comment]
Ok, I have downloaded the patch and the problem has been solved. Thanks for your sharing and help.

**Comment by 1805658335** [comment]
Hi, @km2ii Sorry to bother you again. I seem to be in trouble again. I need your help. This problem occurs when the recording video ends.
![eb20de6582909aba00e23141a6a652e](https://user-images.githubusercontent.com/76620471/162608498-c3c28d68-708b-4c81-9c5c-bdd2d22df296.png)

**Comment by km2ii** [comment]
You did not apply the patch correctly, line 1365 about the time.log is the old code.
Please check the runner version.
![image](https://user-images.githubusercontent.com/55206195/162623476-89703a58-8a28-4273-96a2-5f2b58aa4a24.png)

**Comment by km2ii** [comment]
No need to upgrade to 111, 109a can use this.
> This bug is fixed in versions after 02.14, download 02.26 package (https://workupload.com/file/eu74edfkhS8) or download the patch (https://workupload.com/file/BdtWUuFbZYb) to overwrite the source file location in the TG/ TGMAIN directory.

**Comment by 1805658335** [comment]
Thanks for the tip, now I tested the veai model. But when jumping to veai.exe, a subtitle called loading Ai model appeared. what do I do？

**Comment by km2ii** [comment]
1. It is normal to call veai to pop up command window.
2. If you install more than one version of veai, maybe get stuck loading models, need to uninstall them all and reinstall 2.3.0.

**Comment by 1805658335** [comment]
Now I run the model, and the order of selection is tg -se-veai-ue. Although the prompt of loading the ai model does not appear, when veai.exe appears, it closes immediately, and runGan.exe shows that the model of vea.exe is not running. I just changed the model of veai.exe.
![WJ3VX$ 3~S}NUQY} @05I}H](https://user-images.githubusercontent.com/76620471/163587986-37f83f7b-62d0-4d7f-8011-66afedc0c8b9.png)

**Comment by 1805658335** [comment]
my topaz video Enhance AI is pirated software.
