### ISSUE TITLE
Nvidia GeForce GTX 1650 4G

### ISSUE THREAD

**Issue by mzxcvbnmqg** [km2ii/JP109A_TG-PLUS#65]
Can you install the program?JP109A_TG-PLUS

**Comment by km2ii** [comment]
Sorry, it requires at least 6g RAM to run.

**Comment by Hellgate4** [comment]
RTX 3050 4G works very well for me. Of course, downscales and scaling should be done, but I think this is a problem that can be fully implemented with a little knowledge of the program.
