### ISSUE TITLE
lower cpu load on vspipe denoise

### ISSUE THREAD

**Issue by hentaitaku** [km2ii/JP109A_TG-PLUS#68]
Hi is there a why to lower the cpu load on vspipe.exe for denoise.
Right now the vspipe.exe is running 3x at the same time can it be set to 2 or 1 time to lower the cpu load.

Many Thanks

**Comment by km2ii** [comment]
This is a balanced solution, decreasing will increase the processing time, increasing will often crash, and if needed, a parameter can be added to specify the number of processing threads.

**Comment by hentaitaku** [comment]
What parameter and where?
