### ISSUE TITLE
i meet a  problem :tgmain.exe' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by FrankLinxzx** [km2ii/JP109A_TG-PLUS#69]
tgmain.exe' is not recognized as an internal or external command,
operable program or batch file,is there any solution? thx

![擷取](https://user-images.githubusercontent.com/11344177/166617389-688695aa-c052-43fb-8863-c8beb41863d0.PNG)
e

**Comment by km2ii** [comment]
1.Obviously the file directory is not right, BATCH is a new SRA directory after the 111a version, **this mod does not support the SRA mode mix**.
![image](https://user-images.githubusercontent.com/55206195/166626357-c115ac19-1ece-445a-b9b6-57d98ff38a76.png)
2.The option after tgmain should be NONE.
![image](https://user-images.githubusercontent.com/55206195/166627214-78cbf5d0-5315-4074-8cbc-a49309a46bb1.png)

**Comment by FrankLinxzx** [comment]
> 1.Obviously the file directory is not right, BATCH is a new SRA directory after the 111a version, **this mod does not support the SRA mode mix**. ![image](https://user-images.githubusercontent.com/55206195/166626357-c115ac19-1ece-445a-b9b6-57d98ff38a76.png) 2.The option after tgmain should be NONE. ![image](https://user-images.githubusercontent.com/55206195/166627214-78cbf5d0-5315-4074-8cbc-a49309a46bb1.png)

![image](https://user-images.githubusercontent.com/11344177/166634582-732fe3ac-1f73-478e-8ca1-51e103999153.png)
before the above error apear   ,  is it need to install cuda 11.1? thx

**Comment by km2ii** [comment]
If the running environment is different, first check whether the dll is missing (set config.ini debug = ON), copy the missing dll to the tgmain directory.

**Comment by FrankLinxzx** [comment]
> If the running environment is different, first check whether the dll is missing (set config.ini debug = ON), copy the missing dll to the tgmain directory.

 i put those two files and error gone ,now it works fine.
![image](https://user-images.githubusercontent.com/11344177/166669437-aa3bdcc0-131c-4ce3-a4df-d1e5e074d642.png)
