### ISSUE TITLE
Error after extraction phase

### ISSUE THREAD

**Issue by wobblywhale** [km2ii/JP109A_TG-PLUS#7]
I installed the new TG-PLUS v.1.08.09 on a fresh copy of JavPlayer.

After the Extraction phase JavPlayer displays the error:
```
Failed to convert images
No images have been converted at all
```

I resolved it by manually creating my own config.ini, so it seems it cannot create the config file on the first run.
PS. Thank you for your great work on this.

**Comment by km2ii** [comment]
update v0.1.08.09_patch_01 , fix the create configuration file bug.
https://workupload.com/file/vAvSWQfXKSw

**Comment by wj-max** [comment]
@wobblywhale  如何配置config.inn

**Comment by wj-max** [comment]
@wobblywhale  如何配置 config.ini
