### ISSUE TITLE
Are there any plans to provide a DirectML version of TG-PLUS?

### ISSUE THREAD

**Issue by Dreace** [km2ii/JP109A_TG-PLUS#70]
I'm using an AMD card (6900 XT), but TG-PLUS can only use NVIDIA's CUDA acceleration, so I can only use TG-PLUS via CPU. TecoGAN_111 provided by JavPlayer has been transferred to PyTorch for DirectML, so I can use AMD's GPU for acceleration. Are there any plans to provide a DirectML version of TG-PLUS?

**Comment by FrankLinxzx** [comment]
> I'm using an AMD card (6900 XT), but TG-PLUS can only use NVIDIA's CUDA acceleration, so I can only use TG-PLUS via CPU. TecoGAN_111 provided by JavPlayer has been transferred to PyTorch for DirectML, so I can use AMD's GPU for acceleration. Are there any plans to provide a DirectML version of TG-PLUS?

javplayer is base on Nvidia cuda
