### ISSUE TITLE
watermark patch for javplayer v1.12

### ISSUE THREAD

**Issue by puffer0801** [km2ii/JP109A_TG-PLUS#72]
Is it possible to get one like it was made for older versions? Or at least a guide how to create such a patch (btw I've tried deleting strings like "Modified with JavPlayer" in level0\WmController.dat with no effect at all)...

**Comment by Milincho** [comment]
> Is it possible to get one like it was made for older versions? Or at least a guide how to create such a patch (btw I've tried deleting strings like "Modified with JavPlayer" in level0\WmController.dat with no effect at all)...

I have the same problem. Why did you closed the issue as "completed". Did you find a way to fix this?

**Comment by Milincho** [comment]
> Is it possible to get one like it was made for older versions? Or at least a guide how to create such a patch (btw I've tried deleting strings like "Modified with JavPlayer" in level0\WmController.dat with no effect at all)...

Did you managed to fix this?

**Comment by Ojisansuki** [comment]
I had the same problemHow to remove watermark “Modified with JavPlayer”？
