### ISSUE TITLE
Watermark patch for javplayer v1.12

### ISSUE THREAD

**Issue by Milincho** [km2ii/JP109A_TG-PLUS#73]
Is it available anywhere?

**Comment by dj99999a** [comment]
It would be great to have this patch for v1.12 or to learn how to create it.  Thanks!

**Comment by Milincho** [comment]
Completed? there watermark patch for 1.12 does NOT work. Watermarks still appear in the final video...

**Comment by km2ii** [comment]
Sorry no more patches.

**Comment by Milincho** [comment]
Why? I can understand javski, being the author and living in japan, but an external patch that very few people know about and on top is even timed to stop working?
It's just forcing us to use older and slower versions...

**Comment by dj99999a** [comment]
One last patch for v1.12a please~
