### ISSUE TITLE
Vspipe Entry point not found

### ISSUE THREAD

**Issue by MotleyC** [km2ii/JP109A_TG-PLUS#74]
The file exists in the directory where it is looking. I even tried updating the plugin.
![Screenshot_2](https://user-images.githubusercontent.com/15806477/180006938-7c082932-9ffb-4a2d-9d8e-c20b3ea1ad27.jpg)

**Comment by km2ii** [comment]
not sure about your mean, but test passed.
![180200395-2455e4b3-de76-4525-9c14-0fd8aa5c85ec](https://user-images.githubusercontent.com/55206195/180653337-575d63e9-1eee-4904-a87a-a40110ba550d.png)
