### ISSUE TITLE
Decrypted SE-4X tg-model for JavPlayer

### ISSUE THREAD

**Issue by hentaitaku** [km2ii/JP109A_TG-PLUS#75]
Hi can you give me please the decrypted SE-4X tg-model so i can use it with javplayer.
Right now is the SE-4X tg-model not working with javplayer, think because you have it encrypted with aes.
Or can you give me the aes password key so i can decrypt it.

Like to use just javplayer but with your SE-4X tg-model because it is the best.
Why use javplayer and not your mod because the gpu vram usage is much lower over javplayer.

**Comment by km2ii** [comment]
Sorry, it won't be decrypted because someone is pretending author making money with this free mod on youtube and gumroad.
