### ISSUE TITLE
how to use tg-plus in javplayer

### ISSUE THREAD

**Issue by kanchingkuen02** [km2ii/JP109A_TG-PLUS#76]
Hi, I have installed tg-plus and run config.exe. I dont notice any new options in javplayer? Which options should I use during "record" to make sure that the steps selected in config.exe get executed?

**Comment by suphamster** [comment]
TG-PLUS auto activates if u installed it properly and created config.ini with ConfigTools.exe so there wouldn't be any new options in JP after TG-PLUS installation.
Btw its not revelant to ur question but I'm not much liked latest version of TG-PLUS coz it crashes for me and look of the older version of ConfigTools.exe liked more https://github.com/km2ii/JP109A_TG-PLUS/blob/fbad22c91c468ab751f8c3fb366fbf1694d291c7/Changelogs.md

**Comment by kanchingkuen02** [comment]
Thanks. Will there be any difference if I change the options under record after installing tg-plus? For, example, choosing TG-Z415 instead of TG-STD or choosing VEAI even I do not include it as a step in the config? Does the config override all these options?

**Comment by suphamster** [comment]
As far as I know only changes (like TG-STD/TG-Z415/TG-STD2/TG-AF0 and etc.) in config.ini is matters after installing TG-PLUS. So u need to choose it in ConfigTools.exe or manually edit config.ini. About VEAI I dunno for now but in previous version of TG-PLUS I've enabled it in config.ini also.

**Comment by kanchingkuen02** [comment]
Thanks. Some options like TG-Z415 is available in JP main interface but not in the config tool. Some other like TG-AF0 and TG-STD2 is not available anywhere. I am using 1.11. Is version the reason for this or I have done anything wrong with installation.

**Comment by suphamster** [comment]
> Thanks. Some options like TG-Z415 is available in JP main interface but not in the config tool. Some other like TG-AF0 and TG-STD2 is not available anywhere. I am using 1.11. Is version the reason for this or I have done anything wrong with installation.

Its are on [JP dev twitter](https://twitter.com/Javski2) - 1st one was posted about half year ago and last one about 2 month old and activated by editing config manually (not with GUI). Uploaded both [here](https://workupload.com/file/jq7HMcTNP5w).

**Comment by km2ii** [comment]
That's what happens when you're in a new game, there's so many stories to read.The good thing is there is some strategy by previous people.
