### ISSUE TITLE
My Config.ini gets reset during calculations...

### ISSUE THREAD

**Issue by Milincho** [km2ii/JP109A_TG-PLUS#77]
Why in the hell my Config.ini options get reset to default values *during* calculations??

It doesn't make any sense...

**Comment by Milincho** [comment]
I start the calculations with these settings: https://i.imgur.com/oHU8i5R.png

[main]
mode = TG-PLUS
debug = OFF
autoren = ON

[mplus]
m1 = tecogan:4:TG-AF1
m2 = denoise:td
m3 = veai:4:prob
m4 = 
m5 = 
m6 = 
m7 = 
m8 = 
m9 = 
m10 = 

[others]
imgext = png
skip_imgs = 0
resolution = NoLimited
crf = 22

[veai]
veaipath = C:/Program Files/Topaz Labs LLC/VEAI/veai.exe

[veai_theia_model_opt]
sharpen = 15
enhance-detail = 50
reduce-noise = 0

[veai_proteus_model_opt]
compression = 85
details = 0
blur = 0
noise = 63
halo = 19
preblur = 9

[veaidict]
ahq = ahq-12
alq = alq-13
alqs = alqs-2
amq = amq-13
amqs = amqs-2
gcg = gcg-5
ghq = ghq-5
prob = prob-1
thd = thd-3
thf = thf-4

[Author]
discord = kmkii#8701
gmail = ty4king@gmail.com

-----------------------------------------------------------------------------------------------------------------------------------


Less than an hour later, they are changed back to these: https://i.imgur.com/duyNNx3.png

[main]
mode = TG-PLUS
debug = 	OFF

[mplus]
m1 = tecogan:4:TG-STD
m2 = denoise:tla
m3 = tecogan:4:SE-4X-S2
m4 = veai:4:prob
m5 = downscale:4
m6 = tecogan:4:UE-4X
m7 = 
m8 = 
m9 = 
m10 = 

[others]
imgext = png
skip_imgs = 0
resolution = 1920

[veai]
veaipath = C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe

[veai_theia_model_opt]
sharpen = 15
enhance-detail = 50
reduce-noise = 0

[veai_proteus_model_opt]
compression = 52
details = 24
blur = 9
noise = 7
halo = 12
preblur = -19

[veaidict]
alq = alq-11

[Author]
discord = kmkii#8701
gmail = ty4king@gmail.com

----------------------------------------------------------------------------------------------------

Why in the hell does this happen?

**Comment by Milincho** [comment]
And AGAIN, even with "Read-only" on the fucking config.ini file.

suddenly there's a new window saying this: https://i.imgur.com/tJA9Pfy.png

and my config.ini settings disapper and this shit appears instead:

[main]
mode = TG-PLUS
debug = 	OFF

[mplus]
m1 = tecogan:4:TG-STD
m2 = denoise:tla
m3 = tecogan:4:SE-4X-S2
m4 = veai:4:prob
m5 = downscale:4
m6 = tecogan:4:UE-4X
m7 = 
m8 = 
m9 = 
m10 = 

[others]
imgext = png
skip_imgs = 0
resolution = 1920

[veai]
veaipath = C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe

[veai_theia_model_opt]
sharpen = 15
enhance-detail = 50
reduce-noise = 0

[veai_proteus_model_opt]
compression = 52
details = 24
blur = 9
noise = 7
halo = 12
preblur = -19

[veaidict]
alq = alq-11

[Author]
discord = kmkii#8701
gmail = ty4king@gmail.com

----------------------------------------------------------------------------------------

Why is this happening??

**Comment by km2ii** [comment]
No one has given any feedback about similar problems, but from your screenshot there seems to be some confusion and it seems to be dealing with different folders at the same time (505,498,504).
![image](https://user-images.githubusercontent.com/55206195/186470879-0b0195a4-f14c-4a69-b8cc-2c46fd9a38fb.png)

The final screenshot shows that the config.ini cannot be found and that will regenerated on the first run. It is impossible to determine why, as the mod does not even have a command to delete the f*** config.ini file.


**There are a few settings needed for the mod to work.**
1. no mixed use of sra mode, and safe recording mode is recommended.
![image](https://user-images.githubusercontent.com/55206195/186471246-a30ced38-ceb1-433a-aee6-f8e61900b8be.png)
2. maximum parallel number needs to be set to 1.
![image](https://user-images.githubusercontent.com/55206195/186471362-e44f2e55-35c1-48b7-8c16-fcc02564bd67.png)
3.For versions 110 and above, command line run mode needs to be set for correct display of information.
![image](https://user-images.githubusercontent.com/55206195/186472125-6625c558-808a-4f43-b85c-1511ed13991d.png)
4.It is also recommended to **upgrade to version 1.12a or continue to use version 1.09a**, which are currently the most stable, 1.10-1.12 have many bugs, **keep the latest version of the mod**.

**Comment by Milincho** [comment]
@km2ii  Thanks for the help. Renamed the main folder, renamed the JAVplayer folder I have on C:\ with 1.12a version and it seems to be working now. At least it doesn't reset the config.ini file anymore. I was using it in Safe mode, but with more parallel number of tgmain than 1 and using "Minimized console" mode.

I would LOVE to be able to use 1.12a, and save me 6-8 hours or more of just the extracting process, but as I saw you didn't want to release any working watermark patch for it I decided to revert back to 1.11b, which at least worked for me in the past and doesn't have that horrible "Modified with JAVplayer" watermark.

**Comment by suphamster** [comment]
> @km2ii Thanks for the help. Renamed the main folder, renamed the JAVplayer folder I have on C:\ with 1.12a version and it seems to be working now. At least it doesn't reset the config.ini file anymore. I was using it in Safe mode, but with more parallel number of tgmain than 1 and using "Minimized console" mode.
> 
> Tried v0.2.08.10 yesterday and it gave me errors and refused to work...
Did it throws u such error "[Could not load library cudnn_cnn_infer64_8.dll. Error code 126](https://stackoverflow.com/questions/69879188/could-not-load-library-cudnn-cnn-infer64-8-dll-error-code-126)"
coz it also don't works for me. I was thinking about updating CUDA but didn't tried it yet,,,

**Comment by Milincho** [comment]
> > Tried v0.2.08.10 yesterday and it gave me errors and refused to work...
> 
> Did it throws u such error "[Could not load library cudnn_cnn_infer64_8.dll. Error code 126](https://stackoverflow.com/questions/69879188/could-not-load-library-cudnn-cnn-infer64-8-dll-error-code-126)" coz it also don't works for me. I was thinking about updating CUDA but didn't tried it yet,,,

Tried reinsalling it again with the nvidia dll's and now it's working.

**Comment by suphamster** [comment]
> > > Tried v0.2.08.10 yesterday and it gave me errors and refused to work...
> > 
> > 
> > Did it throws u such error "[Could not load library cudnn_cnn_infer64_8.dll. Error code 126](https://stackoverflow.com/questions/69879188/could-not-load-library-cudnn-cnn-infer64-8-dll-error-code-126)" coz it also don't works for me. I was thinking about updating CUDA but didn't tried it yet,,,
> 
> Tried reinsalling it again with the nvidia dll's and now it's working.

I've tried to delete new nvidia cuda dll and put old ones and now TG-PLUS stopped using GPU and processing images with CPU (much slower) :(. Looks like it's easier just to use older version of TG-PLUS and maybe it would read models from newer version.

**Comment by Milincho** [comment]
A 53 mins movie at 720p too this time on a Ryzen 9 3900X 4.15GHz and a RTX 2080 Super GPU:

Time(extraction)=27m12s

Time(super-resolution)=17h43m4s

Time(encoding)=1h45m12s

Time(combining)=3m35s

are these normal?

**Comment by Milincho** [comment]
> I dunno about SR time (coz it depends on ur settings) but other ecoding and etc seems too slow for ur config. Maybe u are encoding with CPU but not GPU. It's easy to check - if ur CPU load is very high then most likely TG+/JP don't uses ur GPU. Did u set in advaced settings/ffmpeg that JP should use GPU instead CPU?

Mmm...  neither CPU or GPU usage are really high. CPU was around 20% and GPU 30-40%.

This is my config: 

[img]https://i.imgur.com/Amk6VUt.png[/img]

**Comment by Milincho** [comment]
Mmmm...   it seems to be using the CPU at 100% but NOT in multithreading, that's why Process Hacker displays an usage a lot lower than Windows Task Manager.

But it's using GPU also?  30% 3D it says...   does that make sense?

![image](https://user-images.githubusercontent.com/60118859/187532703-622baa06-45c2-43df-a65a-adecbeb8887b.png)

**Comment by suphamster** [comment]
Hm, look line all fine: GPU memory usage is high and CPU is low. Maybe bottleneck is ur slow HDD. Did u tried to do it on SSD?

**Comment by Milincho** [comment]
1280x720 50 mins movie on SSD:

Time(super-resolution)=13h48m57s

Time(encoding)=20m6s

Time(combining)=6m27s

**Comment by suphamster** [comment]
I think that this is quite good results u have now...
