### ISSUE TITLE
default config options give very bad result

### ISSUE THREAD

**Issue by kanchingkuen02** [km2ii/JP109A_TG-PLUS#78]
Spent several days running with the default config and it gives very bad result, when compared to not using tg-plus. Any suggestion on the config options?

**Comment by km2ii** [comment]
1.The default config.ini is used as an example to show the process and functional and is generally applicable to some thin mosaic and not blinking produced before 2016.
2.There are no recommended configurations and often different clips of a film will need to be processed using different configs.
3.Recommended approach is to look in the film library for films that are suitable to cracking, not trying to crack a film by all means. 
4.Quick process of 10-30 seconds use TG-STD>>DENOISE>>VEAI. If get a stable noflicker image, then consider adding other enhancement models such as SE, UE, etc. 
**Don't expect too much. Basically, the good will be better, the bad will be worse.**

**Comment by suphamster** [comment]
Yeah, lools like there are still no universal solution and I'm usually just using it as sandbox to test different settings on 5-8 sec rec.
For example such config for me: 
-------------------------------------------
[mplus]
m1 = {'method': 'tecogan', 'model': 'TG-AF0', 'para': '4X'}
m2 = {'method': 'denoise', 'model': 'tla', 'para': 'medium'}
m3 = {'method': 'tecogan', 'model': 'SE-4X-S2', 'para': '4X'}
---------------------------------------------
gives almost no flicker but looks a bit flat (like 2D).
This is also seems not bad one:
---------------------------------------------
m1 = {'method': 'tecogan', 'model': 'TG-STD2', 'para': '4X'}
m2 = {'method': 'denoise', 'model': 'tla', 'para': 'medium'}
m3 = {'method': 'tecogan', 'model': 'SE-4X-S1', 'para': '4X'}
---------------------------------------------
TG-8X seems gives more realistic and precise image but blurry as hell and seems like not very compatible with other methods...
VEAI is cool tool but I'm using in to upscale fullhd->4k non JAV videos, for clean videos if no need to upscale it not worth (?).

**Comment by kanchingkuen02** [comment]
I also have doubts on veai. Tried SSIS 313.  The mosaic somehow morphed with the underwear. Any example of recommended setting for a particular video to illustrate?
