### ISSUE TITLE
How should the models be selected in the denoise step? 

### ISSUE THREAD

**Issue by 1405040117** [km2ii/JP109A_TG-PLUS#79]
How should the models be selected in the denoise step? What is the case for each model? Which one should be selected for the parameters?

**Comment by km2ii** [comment]
![image](https://user-images.githubusercontent.com/55206195/188436282-8de74990-8eb9-4881-967a-773d6948045d.png)
There are simple instructions in the configuration tool. 3 noise reduction plug-ins are provided here, and the three intensities of high, medium and low are chosen sensibly according to the noise. Note that the removing noise will reduce the sharpness of the image and at the same time may produce distortion, making the images look unnatural.
