### ISSUE TITLE
Problem with python 

### ISSUE THREAD

**Issue by AdamMacchiato** [km2ii/JP109A_TG-PLUS#8]
when going to the m2 denosie:tla step , the cmd show 

py_initialize unable to load the file system code no module named encodings 

when i fix this problem , show other problem , 

fatal python error: py_initialize: can't initialize sys standard streams " io.py " 

TG step and SE-4X-R1 no problem , just only the part of Denosie , 

how can i fix this ?

**Comment by AdamMacchiato** [comment]
the version before update to v.1.08.09, everything is normol , cant work , only 1.08.09 cant work for denoise

**Comment by km2ii** [comment]
try https://workupload.com/file/Vgd3dS85Qbu.

**Comment by AdamMacchiato** [comment]
> try https://workupload.com/file/Vgd3dS85Qbu.

thank you so much , i try this .12 version , denosie fixed , 

but final SE-4X-R1 step , show this Error :

Error Type : < class "valueError>

The Checkpoint verification failed

< Framesummary file corem.py, line 222 in corem >

So what should i do now, thank you so much

**Comment by AdamMacchiato** [comment]
and i just try the code with "SE-4X' without RX1 , its work no problem

**Comment by AdamMacchiato** [comment]
The quality I like the version 1.08.09,is more sharpen, but the speed is much slower than 1.08.12, I am using rtx 3080 with 5950x.

Thank you for your big project 🍻

**Comment by km2ii** [comment]
Deoise reduction can reduce image sharpness and will take a lot of time. This is the reason for the slowdown.
Thanks for testing, the problem with the model is fixed, but it needs to be re-downloaded.
https://workupload.com/file/xGmdZzsZmLp

**Comment by AdamMacchiato** [comment]
yeah , everything has beed fixed , thank you so so so much , for me , i think the SE-4X is more natural , i can see more details and it can fix the noise using TVE , but SE-4X-R1 , loss too much details and the skin too smooth , i perfer SE-4X as well 👍 .

Would you recommond the best quality config.ini setting ? thank you 💯
