### ISSUE TITLE
The new mode "SR-BVPP" have published by the javski.

### ISSUE THREAD

**Issue by tomeleon** [km2ii/JP109A_TG-PLUS#80]
The new mode "SR-BVPP" have published by the javski. Is there any enhance mode plan for it ?

**Comment by tomeleon** [comment]
The new mode "SR-BVPP" have published by the javski. Is there any enhance mode plan for it ?

**Comment by km2ii** [comment]
Tested SR-BVPP and the image seems to be more realistic, the .bat call mode seems less friendly.
