### ISSUE TITLE
fail convert

### ISSUE THREAD

**Issue by nitrolan** [km2ii/JP109A_TG-PLUS#84]
hi can you help me, I did everything as you instructed, it not work
D:\New folder (13)\JavPlayer_111a\TG\BATCH>tgmain.exe 0 TG-STD input4 output4
'tgmain.exe' is not recognized as an internal or external command,
operable program or batch file.

D:\New folder (13)\JavPlayer_111a\TG\BATCH>pause
Press any key to continue . . .

when i run it shows like this, and output have no image

**Comment by km2ii** [comment]
Refer to #69. 111a has many bugs, recommended upgrade to 112a.
