### ISSUE TITLE
Minimize spec for denoise

### ISSUE THREAD

**Issue by kanchingkuen02** [km2ii/JP109A_TG-PLUS#86]
Machine still frozen for days even with testing a segment of a minute or two with the following pipeline:
TG-415 → DENOISE BIG→ SE-4X-S1 → DENOISE TLD→  UE-4X

Current spec:
cpu:i7 4790 
mem: 16g
gpu: 2070

tecogan setting: (tgmain: gpu0/super resolution:gpu0/vrm capacity:8g=max/
ffmpeg setting: (encoding:gpu0/threads:8=cpu max/parallel:4=cpu core no

Any suggestions on software settings and hardware upgrade that would turn the performance to something more bearable? Thanks.

**Comment by kanchingkuen02** [comment]
Thanks for your reply. So denoise uses CPU. I was told by that the freezing is due to CPU being occupied 100% for a prolonged period. How to keep the load of CPU to less than that?

**Comment by suphamster** [comment]
If u read install req properly "The runtime environment is cuda 11.3.1 cudnn-11.3 v8.2.1.32, Please install and configure it." and do what there said u shouldn't have high CPU load coz if u did all correct it would load GPU but CPU load shouldn't be more 50%, Using CUDA/GPU would be several times faster than with just CPU especially coz ur CPU is too slow and not good enough for it,

**Comment by kanchingkuen02** [comment]
Hi, I am puzzled. So does denoise depends on GPU and CPU? (as I get a
different answer from km2ii)  I have installed cuda and cudnn and the path
is set up correctly. How can I  confirm it is loaded correctly by tg-plus?

2022年10月14日(金) 21:57 suphamster ***@***.***>:

**Comment by suphamster** [comment]
U are answering on deleted comment... I've didn't looked it 1st that u are saying about denoise only so I've suggested that u don't installed req tools... About denoise I dunno but most likely ur CPU is rly too weak and I agree with km2ii here.

**Comment by kanchingkuen02** [comment]
I get the CPU part. Just in case, even the new one I get my hand on is still having issues (like the 6700 with 8G) Any parameter or config matters that I can do to stop my machine from freezing and never finishing denoise.

**Comment by km2ii** [comment]
The simple advice is not to use denoise after SE-SR, or use downscale before the 2nd denoise.
--
Don't struggle with this problem, the cause is the [**16G memory is not enough**], and the system cache autoset is too small, the lack of memory will frequently read and write the cache slowing down processing speed, these io and calculations all dependent on cpu, long time high speed operation will trigger protection, cpu downgrade frequency or cause a complete freeze.
