### ISSUE TITLE
Model selection not showing up after configure mod

### ISSUE THREAD

**Issue by grv888** [km2ii/JP109A_TG-PLUS#90]
![image](https://user-images.githubusercontent.com/63555514/197970366-0090448d-6dd8-4504-8003-891aa256f9a5.png)
![image](https://user-images.githubusercontent.com/63555514/197970547-4305bb49-e4fe-4eba-b7b8-b324ab0c2496.png)

**Comment by grv888** [comment]
it's appear in official javplayer also if no tgmain in folder only bvpp.

**Comment by km2ii** [comment]
```
--JavPlayer_112a\ 
    |----ConfigTools.exe
    |----TG\
    |      |----TGMAIN\
    |      |----TG-MODEL\
```

**Comment by grv888** [comment]
![image](https://user-images.githubusercontent.com/63555514/198027811-2ab6da87-be23-4d89-b637-6b9419c314de.png)
Yea but it's still not works, maybe it's because something with cuda?

**Comment by grv888** [comment]
Oh mb sry. Ty solved.
