### ISSUE TITLE
Tecogan-da method fails a few final frames in some output# folders, and leads to failed overall processing

### ISSUE THREAD

**Issue by jrggg** [km2ii/JP109A_TG-PLUS#91]
Hi km2ii!

The new tecogan-da method works amazing! But I've been running into this issue that's causing most of my attempts using it to fail.
- Basically it skips a few random final frames in each output# batch, and leads to the "input# and output# do not match" error in j-player, and causing the video clip processing to fail as a whole. 
- It's always skipping near the end of each batch too (e.g. in an output batch of 1800 frames, it might skip frames 1795-1797).
- This issue always happens if I'm processing clips that are 3mins or longer. For anything less than 2 mins it doesn't happen often/at all.
- I've already tried troubleshooting by updating to newest cuda dlls and libs you recommended.

![image](https://user-images.githubusercontent.com/96934980/200353223-37892731-c32a-4562-9d52-03a60420de36.png)
![image](https://user-images.githubusercontent.com/96934980/200354492-54124acb-fa2d-42cb-b698-2e821f6b09dc.png)

Any help is appreciated!

**Comment by km2ii** [comment]
The logs show that 1800 files have been output correctly and the error is due to stage_start_time.
I need to check the matching issue.

**Comment by jrggg** [comment]
I see - let me know if I can help in any way with additional logs etc!

**Comment by km2ii** [comment]
[v0.2.10.20_patcher](https://workupload.com/file/49E7xDvQsKh)
Overwrite the source files in the TG/TGMAIN, backup first.

> 1. Fix the output error of tecogan-da.
> 2. Fix the output of veai jpg format.

**Comment by jrggg** [comment]
Thanks km2ii you rock! I will test this and let you know.

**Comment by jrggg** [comment]
it seems to be fixed! thanks again.

**Comment by km2ii** [comment]
the resolutions of input?

**Comment by jrggg** [comment]
![image](https://user-images.githubusercontent.com/96934980/202782690-0fe05a1c-02a5-454a-a59b-735b8bb15398.png)
I set it to 1920 resolution limit in the config tool, is that what you mean? The video itself is a standard 1080p video.

**Comment by jrggg** [comment]
Thanks again! Will test this out and let you know.

**Comment by Hellgate4** [comment]
After the first patch, intermittent errors occurred about 100 clips after the second patch, but no errors occurred in the tecoGAN-da. Thank you.

**Comment by jrggg** [comment]
![tg error 3](https://user-images.githubusercontent.com/96934980/202890860-3f475f97-cc36-42c9-9dcf-b3ae5fa26747.png)

km2ii so far so good in terms of the previous error - just wondering is there anything I can do about this new error?

**Comment by km2ii** [comment]
![image](https://user-images.githubusercontent.com/55206195/202905407-92696377-1c83-460b-8e2a-e51e2a2343cd.png)
Manually modify config.ini reduce the n-count.
or
Overwrite the original file and use configtools reduce the value of n-count.
https://workupload.com/file/y9kBca9BFTL
(Modify ConfigTools n-count minimum to 10.)

**Comment by jrggg** [comment]
Thank you!!!
