### ISSUE TITLE
The problem is that I set the output image format to JPG but the TG-PLUS auto change it to PNG to input for VEAI.But there's no selection to set the VEAI's out image format to JPG back!

### ISSUE THREAD

**Issue by tomeleon** [km2ii/JP109A_TG-PLUS#92]
The problem is that I set the output image format to JPG but the TG-PLUS auto change it to PNG to input for VEAI.But there's no selection to set the VEAI's out image format to JPG back! Even if I set it to JPG in the VEAI program before.

**Comment by km2ii** [comment]
[v0.2.10.20_patcher](https://workupload.com/file/49E7xDvQsKh)
Overwrite the source files in the TG/TGMAIN, backup first.

> 1. Fix the output error of tecogan-da.
> 2. Fix the output of veai jpg format.

**Comment by tomeleon** [comment]
Thx!

**Comment by tomeleon** [comment]
A new problem after the patched.The tecogan-da only processed one group of images what numbers set by the N-count. So the number of input images not match the output number.

**Comment by tomeleon** [comment]
OK.Maybe I set the N-count too large.A small unmber has no error
