### ISSUE TITLE
Script exceeded memory limit. consider raising cache size

### ISSUE THREAD

**Issue by asianatrix** [km2ii/JP109A_TG-PLUS#93]
Hi. I have had trouble with TG-PLUS running long videos. I can do 1min sample clips, but 5min scenes will cause my PC to run infinitely until I hard shutdown. Nothing is processing, but GPU is 99% used. I finally turned on error messages in JavPlayer and I saw this one: "script exceeded memory limit. consider raising cache size." Where do I do this? I'm confused. Thanks!

CPU: Ryzen 9 3900
RAM: 32GB
GPU: RTX3070i

**Comment by km2ii** [comment]
Reduce threads of denoise.
![image](https://user-images.githubusercontent.com/55206195/201394604-776e65c7-28fa-471b-83e0-ff950ce35ef1.png)

**Comment by km2ii** [comment]
Haven't encountered this problem. it is recommended to use safe mode, which is still the most stable mode, but requires attention to hard disk space.
