### ISSUE TITLE
Add support for veai 3.0

### ISSUE THREAD

**Issue by hentaitaku** [km2ii/JP109A_TG-PLUS#94]
Hi can you add support for veai 3.0 the 3.0 has cli support over ffmpeg and can make jpg output with same quality as png.
And please add support for 1X right now you have 2X 4X 6X but 1X works to, is not upscale use 100% and Enhance image is good for the 8X models. Will you make a basicVSR-pp AF 8x model?

**Comment by km2ii** [comment]
3.x is very unstable, compared to 2.3 is not a qualitative improvement.
do not support for now.
