### ISSUE TITLE
basicVSR-pp-8x-std doesn't work with fp16

### ISSUE THREAD

**Issue by FaySmash** [km2ii/JP109A_TG-PLUS#96]
When the fp16 option is set to `true` and the `basicVSR-pp-8x-std` Model is used, all resulting images are just black.

**Comment by km2ii** [comment]
Sorry, 10 series cards are not supported.

**Comment by FaySmash** [comment]
> Sorry, 10 series cards are not supported.

This happens with at RTX 3090 as well as GTX 1650

**Comment by km2ii** [comment]
1650 1660 does not work. Turn this off if other cards don't work.

**Comment by FaySmash** [comment]
weird that also my 3090 doesn't work with fp16. I'll stick with fp32 for now
